commerce_payment.commerce_payment_gateway.plugin.ecpay_aio_checkout_payment_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    hash_key:
      type: string
      label: 'Hash key'
    hash_iv:
      type: string
      label: 'Hash IV'
    allowed_payment_methods:
      type: sequence
      label: 'Allowed payment methods'
      sequence:
        - type: string
          label: 'Payment method'
    allowed_remember_credit_card:
      type: boolean
      label: 'Allowed remember customer credit card'
    trade_desc:
      type: string
      label: 'Description for the trade'
